using System;

using DevExpress.ExpressApp.Model;

using Xenial.Framework.Layouts.Items.LeafNodes;

namespace Xenial.Framework.Model.GeneratorUpdaters;

public partial class ModelDetailViewLayoutNodesGeneratorUpdater
{
    internal class EmptySpaceItemBuilder
        : ModelViewLayoutElementFactory<IModelLayoutViewItem, LayoutEmptySpaceItem>
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="emptySpaceItemNode"></param>
        /// <param name="index"></param>
        /// <returns></returns>
        protected override string? CreateAutoGeneratedId(LayoutEmptySpaceItem emptySpaceItemNode, int index)
           => $"EmptySpace-{index}";

        /// <summary>   Creates view layout element. </summary>
        ///
        /// <param name="parentNode">           The parent node. </param>
        /// <param name="emptySpaceItemNode">   The empty space item node. </param>
        ///
        /// <returns>   The new view layout element. </returns>

        protected override IModelLayoutViewItem? CreateViewLayoutElement(IModelNode parentNode, LayoutEmptySpaceItem emptySpaceItemNode)
        {
            var modelLayoutViewItem = parentNode.AddNode<IModelLayoutViewItem>(emptySpaceItemNode.Id);

            return modelLayoutViewItem;
        }
    }
}
