using System;

using Xenial.Framework.Model.GeneratorUpdaters;

namespace DevExpress.ExpressApp.Model.Core;

/// <summary>
/// Class ModelNodesGeneratorUpdatersExtentions.
/// </summary>
/// <autogeneratedoc />
public static partial class ModelNodesGeneratorUpdatersExtentions
{
    /// <summary>   Uses the detail view layout builders. </summary>
    ///
    /// <exception cref="ArgumentNullException">    Thrown when one or more required arguments are
    ///                                             null. </exception>
    ///
    /// <param name="updaters"> The updaters. </param>
    ///
    /// <returns>   ModelNodesGeneratorUpdaters. </returns>

    public static ModelNodesGeneratorUpdaters UseDetailViewLayoutBuilders(this ModelNodesGeneratorUpdaters updaters)
    {
        _ = updaters ?? throw new ArgumentNullException(nameof(updaters));

        updaters.Add(new ModelDetailViewLayoutModelDetailViewItemsNodesGenerator());
        updaters.Add(new ModelDetailViewLayoutNodesGeneratorUpdater());

        return updaters;
    }
}
