using System;

using Xenial;
using Xenial.Framework.TokenEditors.PubTernal;

namespace DevExpress.Persistent.Base
{
    /// <summary>
    /// Class WebViewUriEditorAttribute.
    /// Implements the <see cref="DevExpress.Persistent.Base.EditorAliasAttribute" />
    /// </summary>
    /// <seealso cref="DevExpress.Persistent.Base.EditorAliasAttribute" />
    /// <autogeneratedoc />
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
    [XenialCheckLicence]
    public sealed partial class TokenObjectsEditorAttribute : EditorAliasAttribute
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="TokenObjectsEditorAttribute"/> class.</para>
        /// </summary>
        public TokenObjectsEditorAttribute() : base(TokenEditorAliases.TokenObjectsPropertyEditor) { }
    }

    /// <summary>
    /// Class WebViewUriEditorAttribute.
    /// Implements the <see cref="DevExpress.Persistent.Base.EditorAliasAttribute" />
    /// </summary>
    /// <seealso cref="DevExpress.Persistent.Base.EditorAliasAttribute" />
    /// <autogeneratedoc />
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
    [XenialCheckLicence]
    public sealed partial class TokenStringEditorAttribute : EditorAliasAttribute
    {
        /// <summary>
        /// <para>Initializes a new instance of the <see cref="TokenObjectsEditorAttribute"/> class.</para>
        /// </summary>
        public TokenStringEditorAttribute() : base(TokenEditorAliases.TokenStringPropertyEditor) { }

        /// <summary>
        /// Gets or sets the token drop down show mode.
        /// </summary>
        /// <value>The token drop down show mode.</value>
        /// <autogeneratedoc />
        public TokenDropDownShowMode? TokenDropDownShowMode { get; set; }
    }

    /// <summary>
    /// Enum TokenDropDownShowMode
    /// </summary>
    public enum TokenDropDownShowMode
    {
        /// <summary>
        /// The default
        /// </summary>
        /// <autogeneratedoc />
        Default = 0,
        /// <summary>
        /// The outlook
        /// </summary>
        /// <autogeneratedoc />
        Outlook = 1,
    }
}
