
using DevExpress.ExpressApp.Editors;

namespace Xenial.Framework.Layouts.Items.Base
{
    /// <summary>
    /// 
    /// </summary>
    [XenialCheckLicence]
    public abstract partial record LayoutItemNodeWithAlign : LayoutItemNode
    {
        /// <summary>
        /// Gets or sets the horizontal align.
        /// </summary>
        /// <value>The horizontal align.</value>
        /// <autogeneratedoc />
        public StaticHorizontalAlign? HorizontalAlign { get; set; }

        /// <summary>
        /// Gets or sets the vertical align.
        /// </summary>
        /// <value>The vertical align.</value>
        /// <autogeneratedoc />
        public StaticVerticalAlign? VerticalAlign { get; set; }
    }
}
