using System;

using DevExpress.ExpressApp.Model;
using DevExpress.Utils;

using Xenial;
using Xenial.Framework.Layouts.Items.LeafNodes;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable IDE1006 // Naming Styles

namespace Xenial.Framework.Layouts.Items.Base;

/// <summary>   (Immutable) a layout view item. </summary>
[XenialCheckLicense]
[XenialModelOptions(
    typeof(IModelViewItem), IgnoredMembers = new[]
    {
        nameof(IModelViewItem.Id),
        nameof(IModelViewItem.Index),
        nameof(IModelViewItem.Caption)
    }
)]
public partial record LayoutViewItem : LayoutItemLeaf
{
    //   public Action<IModelViewItem>? ViewItemOptions { get; set; }

    /// <summary>
    /// Creates the specified view item identifier.
    /// </summary>
    /// <param name="viewItemId">The view item identifier.</param>
    /// <returns>Xenial.Framework.Layouts.Items.Base.LayoutViewItem.</returns>
    /// <autogeneratedoc />
    public static LayoutViewItem Create(string viewItemId)
        => new(viewItemId);

    public string ViewItemId { get; init; }

    /// <summary>
    /// Initializes a new instance of the <see cref="LayoutPropertyEditorItem"/> class.
    /// </summary>
    /// <param name="viewItemId">The property editor.</param>
    /// <autogeneratedoc />
    public LayoutViewItem(string viewItemId)
        => (ViewItemId, Id) = (viewItemId, Slugifier.GenerateSlug(viewItemId));
}
