using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;

using Xenial.Framework.Layouts;

namespace Xenial.Framework.Model
{
    /// <summary>
    /// Interface IModelGeneratedView
    /// </summary>
    /// <autogeneratedoc />
    public interface IModelObjectGeneratedView
    {
        /// <summary>
        /// Gets the type of the generator.
        /// </summary>
        /// <value>The type of the generator.</value>
        /// <autogeneratedoc />
        Type? GeneratorType { get; }
    }

    /// <summary>
    /// Class ModelGeneratedViewDomainLogic.
    /// </summary>
    /// <autogeneratedoc />
#pragma warning disable CA1707 //By convention
    [DomainLogic(typeof(IModelObjectGeneratedView))]
    public static class ModelObjectGeneratedViewDomainLogic
    {
        /// <summary>
        /// Gets the type of the generator.
        /// </summary>
        /// <param name="modelView">The model view.</param>
        /// <returns>System.Nullable&lt;Type&gt;.</returns>
        /// <autogeneratedoc />
        public static Type? Get_GeneratorType(IModelObjectGeneratedView modelView)
        {
            _ = modelView ?? throw new ArgumentNullException(nameof(modelView));

            if (modelView is IModelObjectView objectView)
            {
                if (objectView.ModelClass == null)
                {
                    return null;
                }
                var attributes = objectView.ModelClass.TypeInfo.FindAttributes<DetailViewLayoutBuilderAttribute>();
                var attribute = attributes.FirstOrDefault(); //TODO: Multiple DetailViews
                return attribute?.GeneratorType;
            }

            return null;
        }
    }
#pragma warning restore CA1707
}
