using System;
using System.Collections.Generic;
using System.Text;

using DevExpress.Persistent.Base;

using Xenial.Framework.Base;

namespace Xenial.FeatureCenter.Module.BusinessObjects.Editors
{
    [DefaultClassOptions]
    [Singleton(AutoCommit = true)]
    public partial class StepProgressBarEnumEditorPersistentDemo
    {
        protected override string UsagePath => "BusinessObjects/Editors/StepProgressBarEnumEditorDemo.Usage.md";

        protected override IEnumerable<RequiredNuget> GetRequiredModules() => new[]
        {
            new RequiredNuget("StepProgressEditors"),
            new RequiredNuget("StepProgressEditors", AvailablePlatform.Win),
        };

        /// <summary>
        /// Adds the installation section.
        /// </summary>
        /// <param name="sb">The sb.</param>
        /// <autogeneratedoc />
        protected override void AddInstallationSection(StringBuilder sb)
        {
            base.AddInstallationSection(sb);

            sb.AppendLine(new TabGroup
            {
                Tabs = new()
                {
                    new("Using Modules", "fas fa-code")
                    {
                        MarkDown = @"

#### Common Module

```cs
public class MyProjectModule : ModuleBase
{
    protected override ModuleTypeList GetRequiredModuleTypesCore()
    {
        var moduleTypes = base.GetRequiredModuleTypesCore();
        
        moduleTypes.Add(typeof(XenialStepProgressEditorsModule));
        
        return moduleTypes;
    }
}
```

#### Windows Forms Module

```cs
public class MyProjectWindowsFormsModule : ModuleBase
{
    protected override ModuleTypeList GetRequiredModuleTypesCore()
    {
        var moduleTypes = base.GetRequiredModuleTypesCore();
        
        moduleTypes.Add(typeof(XenialStepProgressEditorsWindowsFormsModule));
        
        return moduleTypes;
    }
}
```

"
                    },
                    new("Using Feature Slices", "fas fa-pizza-slice")
                    {
                        MarkDown = @"
#### Common Module

```cs
public class MyProjectModule : ModuleBase
{
    protected override void RegisterEditorDescriptors(EditorDescriptorsFactory editorDescriptorsFactory)
    {
        base.RegisterEditorDescriptors(editorDescriptorsFactory);
        editorDescriptorsFactory.UseStepProgressEnumPropertyEditors();
    }
}
```

#### Windows Forms Module

```cs
public class MyProjectWindowsFormsModule : ModuleBase
{
    protected override void RegisterEditorDescriptors(EditorDescriptorsFactory editorDescriptorsFactory)
    {
        base.RegisterEditorDescriptors(editorDescriptorsFactory);
        editorDescriptorsFactory.UseStepProgressEnumPropertyEditorsWin();
    }
    
    public override void AddGeneratorUpdaters(ModelNodesGeneratorUpdaters updaters)
    {
        base.AddGeneratorUpdaters(updaters);
        
        //This is optional. You need this only for nullable enumeration properties in combination with the EditorAliasAttribute, StepProgressEnumEditorAttribute or ModelBuilders when using DevExpress version <= 20.2.4
        //See: https://supportcenter.devexpress.com/ticket/details/t962834/registering-an-editor-alias-for-nullable-types for more information
        updaters.UseStepProgressEnumPropertyEditors();
    }
}
```

"

                    }
                }
            }.ToString());
        }
    }
}
