namespace Xenial.Framework.DevTools;

/// <summary>
/// Class XenialDevToolsModule.
/// Implements the <see cref="Xenial.Framework.XenialModuleBase" />
/// </summary>
/// <seealso cref="Xenial.Framework.XenialModuleBase" />
/// <autogeneratedoc />
[XenialCheckLicense]
public sealed partial class XenialDevToolsModule : XenialModuleBase
{
}
