using System;
using System.Collections.Generic;
using System.Linq;

using Xenial.Framework.Badges.Win;

namespace Xenial.Framework.Badges.Win
{
    internal static class ControllerTypeList
    {
        /// <summary>   Gets a list of types of the controllers. </summary>
        ///
        /// <value> A list of types of the controllers. </value>

        public static Type[] ControllerTypes { get; } = new[]
        {
            typeof(XenialBadgesWindowsFormsNavigationWindowController)
        };
    }
}

namespace DevExpress.ExpressApp
{
    /// <summary>
    /// Class ControllerTypeListExtension.
    /// </summary>
    /// <autogeneratedoc />
    public static partial class ControllerTypeListExtension
    {
        /// <summary>   Uses the xenial badges windows forms controller types. </summary>
        ///
        /// <param name="types">    The types. </param>
        ///
        /// <returns>   IEnumerable&lt;Type&gt;. </returns>

        public static IEnumerable<Type> UseXenialBadgesWindowsFormsControllers(this IEnumerable<Type> types)
            => types.Concat(ControllerTypeList.ControllerTypes);
    }
}
