//HintName: GeneratesSimpleActionWhenDefined.GeneratesSimpleActionWhenDefined.g.cs
// <auto-generated />

using System;
using System.IO;
using System.Runtime.CompilerServices;

namespace MyActions
{
    [CompilerGenerated]
    partial class GeneratesSimpleActionWhenDefined
    {
        partial void Execute(object targetObject);
    }
    
}
