//HintName: ImageNamesWithSizes.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

namespace MyProject
{
    [CompilerGenerated]
    partial class ImageNamesWithSizes
    {
    }
}
