//HintName: DoesEmitSimpleProperties.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

using Xenial.Framework.Layouts;
using Xenial.Framework.Layouts.Items;
using Xenial.Framework.Layouts.Items.Base;
using Xenial.Framework.Layouts.Items.LeafNodes;

namespace MyProject
{
    [CompilerGenerated]
    partial class DoesEmitSimpleProperties
    {
        private struct PropertyIdentifier
        {
            private string propertyName;
            public string PropertyName { get { return this.propertyName; } }
            
            private PropertyIdentifier(string propertyName)
            {
                this.propertyName = propertyName;
            }
            
            public static implicit operator string(PropertyIdentifier identifier)
            {
                return identifier.PropertyName;
            }
            
            public static PropertyIdentifier Create(string propertyName)
            {
                return new PropertyIdentifier(propertyName);
            }
        }
        
        private partial struct Property
        {
            public static PropertyIdentifier StringProperty { get { return PropertyIdentifier.Create("StringProperty"); } }
            
            public static PropertyIdentifier IntProperty { get { return PropertyIdentifier.Create("IntProperty"); } }
            
            public static PropertyIdentifier BoolProperty { get { return PropertyIdentifier.Create("BoolProperty"); } }
            
            public static PropertyIdentifier ByteProperty { get { return PropertyIdentifier.Create("ByteProperty"); } }
            
            public static PropertyIdentifier DecimalProperty { get { return PropertyIdentifier.Create("DecimalProperty"); } }
            
        }
        
        private partial struct Editor
        {
            public static LayoutPropertyEditorItem StringProperty { get { return LayoutPropertyEditorItem.Create("StringProperty"); } }
            
            public static LayoutPropertyEditorItem IntProperty { get { return LayoutPropertyEditorItem.Create("IntProperty"); } }
            
            public static LayoutPropertyEditorItem BoolProperty { get { return LayoutPropertyEditorItem.Create("BoolProperty"); } }
            
            public static LayoutPropertyEditorItem ByteProperty { get { return LayoutPropertyEditorItem.Create("ByteProperty"); } }
            
            public static LayoutPropertyEditorItem DecimalProperty { get { return LayoutPropertyEditorItem.Create("DecimalProperty"); } }
            
        }
    }
}
