//HintName: MyPartialClass.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

namespace MyProject
{
    [CompilerGenerated]
    partial class MyPartialClass
    {
        internal const string DomainComponent_DetailView = "DomainComponent_DetailView";
        internal const string DomainComponent_ListView = "DomainComponent_ListView";
        internal const string DomainComponent_LookupListView = "DomainComponent_LookupListView";
    }
}
