using System;

using DevExpress.ExpressApp.Editors;

namespace Xenial.Framework.WebView.Win
{
    /// <summary>
    /// Class XenialWebViewWindowsFormsModule.
    /// Implements the <see cref="Xenial.Framework.XenialModuleBase" />
    /// </summary>
    /// <seealso cref="Xenial.Framework.XenialModuleBase" />
    /// <autogeneratedoc />
    [XenialCheckLicence]
    public sealed partial class XenialWebViewWindowsFormsModule : XenialModuleBase
    {
        /// <summary>
        /// Registers the editor descriptors.
        /// </summary>
        /// <param name="editorDescriptorsFactory">The editor descriptors factory.</param>
        /// <autogeneratedoc />
        protected override void RegisterEditorDescriptors(EditorDescriptorsFactory editorDescriptorsFactory)
        {
            base.RegisterEditorDescriptors(editorDescriptorsFactory);
            editorDescriptorsFactory.UseWebViewUriPropertyEditorWin();
        }
    }
}
