using System;
using System.Collections;
using System.Collections.Generic;

using Xenial.Framework.Layouts.ColumnItems;

#pragma warning disable CA1033 //Seal Type -> By Design
#pragma warning disable CA1710 //Rename Type to end in Collection -> By Design
#pragma warning disable CA2227 //Collection fields should not have a setter -> By Design

namespace Xenial.Framework.Layouts
{
    /// <summary>
    /// Class Columns.
    /// </summary>
    /// <autogeneratedoc />
    public class Columns : IEnumerable<Column>
    {
        IEnumerator<Column> IEnumerable<Column>.GetEnumerator() => Items.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Items.GetEnumerator();

        /// <summary>
        /// Gets or sets the columns.
        /// </summary>
        /// <value>The columns.</value>
        /// <autogeneratedoc />
        public ColumnCollection<Column> Items { get; set; } = new();

        /// <summary>
        /// Adds the specified column.
        /// </summary>
        /// <param name="column">The column.</param>
        /// <autogeneratedoc />
        public void Add(Column column)
            => Items.Add(column);

    }
}
