#pragma warning disable CA1724 //Conflicts with Winforms: Should not conflict in practice

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text;

using Xenial.Framework.Layouts.Items.Base;
using Xenial.Framework.Layouts.Items.LeafNodes;

namespace Xenial.Framework.Layouts
{
    /// <summary>
    /// 
    /// </summary>
    [XenialCheckLicence]
    public partial record LayoutBuilder<TModelClass>
        where TModelClass : class
    {
        /// <summary>
        /// Properties the editor.
        /// </summary>
        /// <typeparam name="TProperty">The type of the t property.</typeparam>
        /// <param name="expression">The expression.</param>
        /// <returns>Xenial.Framework.Layouts.Items.LayoutPropertyEditorItem&lt;TModelClass&gt;.</returns>
        /// <autogeneratedoc />
        public LayoutPropertyEditorItem<TModelClass> PropertyEditor<TProperty>(Expression<Func<TModelClass, TProperty>> expression)
            => LayoutPropertyEditorItem<TModelClass>.CreatePropertyEditor(expression);

        /// <summary>
        /// Empties the space item.
        /// </summary>
        /// <returns>Xenial.Framework.Layouts.Items.LayoutEmptySpaceItem.</returns>
        /// <autogeneratedoc />
        public LayoutEmptySpaceItem EmptySpaceItem()
            => LayoutEmptySpaceItem.Create();

        /// <summary>
        /// Empties the space item.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Xenial.Framework.Layouts.Items.LayoutEmptySpaceItem.</returns>
        /// <autogeneratedoc />
        public LayoutEmptySpaceItem EmptySpaceItem(string id)
            => LayoutEmptySpaceItem.Create(id);
    }
}
