using System;
using System.ComponentModel;

namespace Xenial.Framework.Layouts;

/// <summary>
/// Class ListViewColumnsBuilderAttribute. This class cannot be inherited. Implements the
/// <see cref="System.Attribute" />
/// </summary>
///
/// <seealso cref="Attribute"/>
/// <seealso cref="System.Attribute">   <autogeneratedoc /></seealso>

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
[XenialCheckLicense]
public abstract partial class ColumnsBuilderAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ColumnsBuilderAttribute"/> class.
    /// </summary>

    protected ColumnsBuilderAttribute() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="ColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="generatorType">    Type of the column builder. </param>

    protected ColumnsBuilderAttribute(Type generatorType)
        => GeneratorType = generatorType ?? throw new ArgumentNullException(nameof(generatorType));

    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute" /> class.
    /// </summary>
    ///
    /// <param name="generatorType">            Type of the generator. </param>
    /// <param name="buildColumnsMethodName">   Name of the build columns method. </param>

    protected ColumnsBuilderAttribute(Type generatorType, string buildColumnsMethodName)
        => (GeneratorType, BuildColumnsMethodName)
        = (
            generatorType ?? throw new ArgumentNullException(nameof(generatorType)),
            buildColumnsMethodName ?? throw new ArgumentNullException(nameof(buildColumnsMethodName))
        );

    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="buildColumnsDelegate"> The build columns delegate. </param>

    [EditorBrowsable(EditorBrowsableState.Never)]
    protected ColumnsBuilderAttribute(BuildColumnsFunctor buildColumnsDelegate)
        => BuildColumnsDelegate = buildColumnsDelegate;

    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="buildColumnsMethodName">   Name of the build columns method. </param>

    protected ColumnsBuilderAttribute(string buildColumnsMethodName)
        => BuildColumnsMethodName = buildColumnsMethodName;

    /// <summary>   Gets the type of the columns builder. </summary>
    ///
    /// <value> The type of the columns builder. </value>

    public Type? GeneratorType { get; internal set; }

    /// <summary>   Gets the build columns delegate. </summary>
    ///
    /// <value> The build columns delegate. </value>

    public BuildColumnsFunctor? BuildColumnsDelegate { get; internal set; }

    /// <summary>   Gets the name of the build layout method. </summary>
    ///
    /// <value> The name of the build layout method. </value>

    public string? BuildColumnsMethodName { get; internal set; }

    /// <summary>
    /// Gets or sets the list view identifier.
    /// </summary>
    /// <value>The list view identifier.</value>
    public string? ViewId { get; set; }
}

/// <summary>
/// Class ListViewColumnsBuilderAttribute. This class cannot be inherited. Implements the
/// <see cref="System.Attribute" />
/// </summary>
///
/// <seealso cref="Attribute"/>
/// <seealso cref="System.Attribute">   <autogeneratedoc /></seealso>

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
[XenialCheckLicense]
public sealed partial class ListViewColumnsBuilderAttribute : ColumnsBuilderAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute"/> class.
    /// </summary>

    public ListViewColumnsBuilderAttribute() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="generatorType">    Type of the column builder. </param>

    public ListViewColumnsBuilderAttribute(Type generatorType) : base(generatorType) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute" /> class.
    /// </summary>
    ///
    /// <param name="generatorType">            Type of the generator. </param>
    /// <param name="buildColumnsMethodName">   Name of the build columns method. </param>

    public ListViewColumnsBuilderAttribute(Type generatorType, string buildColumnsMethodName)
        : base(generatorType, buildColumnsMethodName) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="buildColumnsDelegate"> The build columns delegate. </param>

    [EditorBrowsable(EditorBrowsableState.Never)]
    public ListViewColumnsBuilderAttribute(BuildColumnsFunctor buildColumnsDelegate)
        : base(buildColumnsDelegate) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="ListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="buildColumnsMethodName">   Name of the build columns method. </param>

    public ListViewColumnsBuilderAttribute(string buildColumnsMethodName)
        : base(buildColumnsMethodName) { }
}

/// <summary>
/// Class LookupListViewColumnsBuilderAttribute. This class cannot be inherited. Implements the
/// <see cref="System.Attribute" />
/// </summary>
///
/// <seealso cref="Attribute"/>
/// <seealso cref="System.Attribute">   <autogeneratedoc /></seealso>

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
[XenialCheckLicense]
public sealed partial class LookupListViewColumnsBuilderAttribute : ColumnsBuilderAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="LookupListViewColumnsBuilderAttribute"/> class.
    /// </summary>

    public LookupListViewColumnsBuilderAttribute() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="LookupListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="generatorType">    Type of the column builder. </param>

    public LookupListViewColumnsBuilderAttribute(Type generatorType) : base(generatorType) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="LookupListViewColumnsBuilderAttribute" /> class.
    /// </summary>
    ///
    /// <param name="generatorType">            Type of the generator. </param>
    /// <param name="buildColumnsMethodName">   Name of the build columns method. </param>

    public LookupListViewColumnsBuilderAttribute(Type generatorType, string buildColumnsMethodName)
        : base(generatorType, buildColumnsMethodName) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="LookupListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="buildColumnsDelegate"> The build columns delegate. </param>

    [EditorBrowsable(EditorBrowsableState.Never)]
    public LookupListViewColumnsBuilderAttribute(BuildColumnsFunctor buildColumnsDelegate)
        : base(buildColumnsDelegate) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="LookupListViewColumnsBuilderAttribute"/> class.
    /// </summary>
    ///
    /// <param name="buildColumnsMethodName">   Name of the build columns method. </param>

    public LookupListViewColumnsBuilderAttribute(string buildColumnsMethodName)
        : base(buildColumnsMethodName) { }
}

/// <summary>   Delegate BuildColumnsDelegate. </summary>
///
/// <returns>   Layout. </returns>

public delegate Columns BuildColumnsFunctor();
