namespace Xenial.Framework.Layouts.Items.PubTernal
{
    /// <summary>
    /// Interface ILayoutElementWithCaption
    /// </summary>
    /// <autogeneratedoc />
    public interface ILayoutElementWithCaption
    {
        /// <summary>
        /// Gets or sets the caption.
        /// </summary>
        /// <value>The caption.</value>
        /// <autogeneratedoc />
        string? Caption { get; set; }
    }
}
