using System;
using System.Collections.Generic;
using System.Linq;

using Xenial.Framework.Win.SystemModule;

namespace Xenial.Framework.Win.SystemModule
{
    internal static class ControllerTypeList
    {
        public static Type[] ControllerTypes { get; } = new[]
        {
            typeof(XenialAdvancedModelEditorActionsViewController)
        };
    }
}

namespace DevExpress.ExpressApp
{
    /// <summary>
    /// Class ControllerTypeListExtension.
    /// </summary>
    /// <autogeneratedoc />
    public static partial class ControllerTypeListExtension
    {
        /// <summary>
        /// Uses all Controllers of the XenialSystemWindowsFormsModule
        /// </summary>
        /// <param name="types"></param>
        /// <returns></returns>
        public static IEnumerable<Type> UseXenialWindowsFormsControllers(this IEnumerable<Type> types)
            => types.Concat(ControllerTypeList.ControllerTypes);


    }
}
