//HintName: ControllerTypeList.g.cs
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace MyProject
{
    [CompilerGenerated]
    partial class ControllerTypeList
    {
        internal static readonly IEnumerable<Type> ControllerTypes = new Type[]
        {
            typeof(MyProject.MyController),
        };
    }
}
