//HintName: DoesEmitSimpleRelation.DoesEmitSimpleRelationForParent.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

using Xenial.Framework.Layouts;
using Xenial.Framework.Layouts.Items;
using Xenial.Framework.Layouts.Items.Base;
using Xenial.Framework.Layouts.Items.LeafNodes;

namespace MyProject
{
    [CompilerGenerated]
    partial class DoesEmitSimpleRelationForParent
    {
        
        private partial struct Constants
        {
            public const string Parents = "Parents";
        }
        
        private partial struct Editor
        {
            public static LayoutPropertyEditorItem Parents { get { return LayoutPropertyEditorItem.Create("Parents"); } }
        }
    }
}
