//HintName: RemovesNestedListView.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

namespace MyProject
{
    [CompilerGenerated]
    partial class MyPartialClass
    {
        internal const string PersistentChildObject_DetailView = "PersistentChildObject_DetailView";
        internal const string PersistentChildObject_ListView = "PersistentChildObject_ListView";
        internal const string PersistentChildObject_LookupListView = "PersistentChildObject_LookupListView";
        internal const string PersistentObject_DetailView = "PersistentObject_DetailView";
        internal const string PersistentObject_ListView = "PersistentObject_ListView";
        internal const string PersistentObject_LookupListView = "PersistentObject_LookupListView";
    }
}
