//HintName: MyPartialClass.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

namespace MyProject
{
    [CompilerGenerated]
    partial class MyPartialClass
    {
        internal const string NonPersistentObject_DetailView = "NonPersistentObject_DetailView";
        internal const string NonPersistentObject_ListView = "NonPersistentObject_ListView";
        internal const string NonPersistentObject_LookupListView = "NonPersistentObject_LookupListView";
    }
}
