//HintName: BasicDecimalProperty.BasicDecimalProperty.Builder.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

namespace MyProject
{
    [CompilerGenerated]
    internal partial class BasicDecimalPropertyBuilder : BasicDecimalPropertyBuilder<MyProject.BasicDecimalProperty, BasicDecimalPropertyBuilder> { }
    
    [CompilerGenerated]
    internal abstract partial class BasicDecimalPropertyBuilder<TClass, TBuilder>
        where TClass : MyProject.BasicDecimalProperty
        where TBuilder : BasicDecimalPropertyBuilder<TClass, TBuilder>
    {
        protected TBuilder This
        {
            get
            {
                return (TBuilder)this;
            }
        }
        
        protected virtual TClass CreateTarget()
        {
            return (TClass)new MyProject.BasicDecimalProperty();
        }
        
        protected decimal DecimalProperty { get; set; }
        protected bool WasDecimalPropertyCalled { get; private set; }
        
        public TBuilder WithDecimalProperty(decimal decimalProperty)
        {
            this.DecimalProperty = decimalProperty;
            this.WasDecimalPropertyCalled = true;
            return This;
        }
        
        protected decimal DecimalProperty2 { get; set; }
        protected bool WasDecimalProperty2Called { get; private set; }
        
        public TBuilder WithDecimalProperty2(decimal decimalProperty2)
        {
            this.DecimalProperty2 = decimalProperty2;
            this.WasDecimalProperty2Called = true;
            return This;
        }
        
        public virtual TClass Build()
        {
            TClass target = this.CreateTarget();
            
            if(this.WasDecimalPropertyCalled)
            {
                target.DecimalProperty = this.DecimalProperty;
            }
            
            if(this.WasDecimalProperty2Called)
            {
                target.DecimalProperty2 = this.DecimalProperty2;
            }
            
            return target;
        }
    }
}
