//HintName: BasicXpoWithNotGeneratedCtorIntKey.BasicXpoWithNotGeneratedCtorIntKey.Builder.g.cs
// <auto-generated />

using System;
using System.Runtime.CompilerServices;

namespace MyProject
{
    [CompilerGenerated]
    internal partial class BasicXpoWithNotGeneratedCtorIntKeyBuilder : BasicXpoWithNotGeneratedCtorIntKeyBuilder<MyProject.BasicXpoWithNotGeneratedCtorIntKey, BasicXpoWithNotGeneratedCtorIntKeyBuilder> { }
    
    [CompilerGenerated]
    internal abstract partial class BasicXpoWithNotGeneratedCtorIntKeyBuilder<TClass, TBuilder>
        where TClass : MyProject.BasicXpoWithNotGeneratedCtorIntKey
        where TBuilder : BasicXpoWithNotGeneratedCtorIntKeyBuilder<TClass, TBuilder>
    {
        protected DevExpress.Xpo.Session Session { get; set; }
        protected bool WasSessionSet { get; private set; }
        
        public TBuilder WithSession(DevExpress.Xpo.Session session)
        {
            this.Session = session;
            this.WasSessionSet = true;
            return This;
        }
        
        protected TBuilder This
        {
            get
            {
                return (TBuilder)this;
            }
        }
        
        protected virtual TClass CreateTarget()
        {
            if(this.WasSessionSet)
            {
                return (TClass)new MyProject.BasicXpoWithNotGeneratedCtorIntKey(this.Session);
            }
            
            throw new System.InvalidOperationException($"Could not create instance of type [MyProject.BasicXpoWithNotGeneratedCtorIntKey] without a Session.{System.Environment.NewLine}Make sure to use the [WithSession] method when using the [{this.GetType().FullName}] type.");
        }
        
        protected int KeyProperty { get; set; }
        protected bool WasKeyPropertyCalled { get; private set; }
        
        public TBuilder WithKeyProperty(int keyProperty)
        {
            this.KeyProperty = keyProperty;
            this.WasKeyPropertyCalled = true;
            return This;
        }
        
        protected string OwnStringProperty { get; set; }
        protected bool WasOwnStringPropertyCalled { get; private set; }
        
        public TBuilder WithOwnStringProperty(string ownStringProperty)
        {
            this.OwnStringProperty = ownStringProperty;
            this.WasOwnStringPropertyCalled = true;
            return This;
        }
        
        public virtual TClass Build()
        {
            TClass target = this.CreateTarget();
            
            if(this.WasKeyPropertyCalled)
            {
                target.KeyProperty = this.KeyProperty;
            }
            
            if(this.WasOwnStringPropertyCalled)
            {
                target.OwnStringProperty = this.OwnStringProperty;
            }
            
            return target;
        }
    }
}
