using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;

using Xenial.Framework.Model.Core;
using Xenial.Framework.TokenEditors.Model;
using Xenial.Framework.TokenEditors.PubTernal;

namespace Xenial.Framework.TokenEditors.Model
{
    /// <summary>
    /// Interface ITokenStringModelMember
    /// </summary>
    /// <autogeneratedoc />
    public interface ITokenStringModelMember
    {
        /// <summary>
        /// Gets or sets the token drop down show mode.
        /// This value has only an effect in WindowsForms
        /// </summary>
        /// <value>The token drop down show mode.</value>
        /// <autogeneratedoc />
        [ModelBrowsable(typeof(TokenStringEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenStringPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenStringPropertyEditor + "." + nameof(TokenDropDownShowMode))]
        [Description("Gets or sets the token drop down show mode.\r\nThis value has only an effect in WindowsForms")]
        TokenDropDownShowMode? TokenDropDownShowMode { get; set; }

        /// <summary>
        /// Gets or sets the token popup filter mode.
        /// </summary>
        /// <value>The token popup filter mode.</value>
        /// <autogeneratedoc />
        [ModelBrowsable(typeof(TokenStringEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenStringPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenStringPropertyEditor + "." + nameof(TokenPopupFilterMode))]
        [Description("Gets or sets the token popup filter mode.")]
        TokenPopupFilterMode? TokenPopupFilterMode { get; set; }
    }

    /// <summary>
    /// Interface ITokenStringModelPropertyEditor
    /// </summary>
    /// <autogeneratedoc />
    public interface ITokenStringModelPropertyEditor
    {
        /// <summary>
        /// Gets or sets the token drop down show mode.
        /// This value has only an effect in WindowsForms
        /// </summary>
        /// <value>The token drop down show mode.</value>
        /// <autogeneratedoc />
        [ModelValueCalculator(nameof(IModelPropertyEditor.ModelMember), typeof(ITokenStringModelMember), nameof(ITokenStringModelMember.TokenDropDownShowMode))]
        [ModelBrowsable(typeof(TokenStringEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenStringPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenStringPropertyEditor + "." + nameof(TokenDropDownShowMode))]
        [Description("Gets or sets the token drop down show mode.\r\nThis value has only an effect in WindowsForms")]
        TokenDropDownShowMode? TokenDropDownShowMode { get; set; }

        /// <summary>
        /// Gets or sets the token popup filter mode.
        /// </summary>
        /// <value>The token popup filter mode.</value>
        /// <autogeneratedoc />
        [ModelValueCalculator(nameof(IModelPropertyEditor.ModelMember), typeof(ITokenStringModelMember), nameof(ITokenStringModelMember.TokenPopupFilterMode))]
        [ModelBrowsable(typeof(TokenStringEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenStringPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenStringPropertyEditor + "." + nameof(TokenPopupFilterMode))]
        [Description("Gets or sets the token popup filter mode.")]
        TokenPopupFilterMode? TokenPopupFilterMode { get; set; }
    }

    /// <summary>
    /// Class TokenStringEditorTypeVisibilityCalculator. This class cannot be inherited.
    /// Implements the <see cref="Xenial.Framework.Model.Core.EditorTypeVisibilityCalculator" />
    /// </summary>
    /// <seealso cref="Xenial.Framework.Model.Core.EditorTypeVisibilityCalculator" />
    /// <autogeneratedoc />
    public sealed class TokenStringEditorTypeVisibilityCalculator : EditorTypeAliasVisibilityCalculator
    {
        /// <summary>
        /// Gets the name of the editor alias.
        /// </summary>
        /// <value>The name of the editor alias.</value>
        /// <autogeneratedoc />
        protected override string EditorAliasName => TokenEditorAliases.TokenStringPropertyEditor;
    }

#pragma warning disable CA1707 //Convention by XAF

    /// <summary>
    /// Class TokenStringModelMemberDomainLogic.
    /// </summary>
    /// <autogeneratedoc />
    [DomainLogic(typeof(ITokenStringModelMember))]
    public static class TokenStringModelMemberDomainLogic
    {
        /// <summary>
        /// Gets the token drop down show mode.
        /// </summary>
        /// <param name="modelMember">The model member.</param>
        /// <returns>DevExpress.Persistent.Base.TokenDropDownShowMode?.</returns>
        /// <autogeneratedoc />
        public static TokenDropDownShowMode? Get_TokenDropDownShowMode(IModelMember modelMember)
        {
            _ = modelMember ?? throw new ArgumentNullException(nameof(modelMember));
            var attribute = modelMember.MemberInfo.FindAttribute<TokenStringEditorAttribute>();
            if (attribute is not null)
            {
                return attribute.DropDownShowMode;
            }
            return null;
        }

        /// <summary>
        /// Gets the token popup filter mode.
        /// </summary>
        /// <param name="modelMember">The model member.</param>
        /// <returns>DevExpress.Persistent.Base.TokenPopupFilterMode?.</returns>
        /// <autogeneratedoc />
        public static TokenPopupFilterMode? Get_TokenPopupFilterMode(IModelMember modelMember)
        {
            _ = modelMember ?? throw new ArgumentNullException(nameof(modelMember));
            var attribute = modelMember.MemberInfo.FindAttribute<TokenStringEditorAttribute>();
            if (attribute is not null)
            {
                return attribute.PopupFilterMode;
            }
            return null;
        }
    }
#pragma warning restore CA1707
}

namespace DevExpress.ExpressApp.Model
{
    /// <summary>
    /// Class ModelInterfaceExtendersLayoutBuilderExtensions.
    /// </summary>
    /// <autogeneratedoc />
    public static partial class ModelInterfaceExtendersTokenEditorsExtensions
    {
        /// <summary>
        /// Uses the token string property editors.
        /// </summary>
        /// <param name="extenders">The extenders.</param>
        /// <returns>DevExpress.ExpressApp.Model.ModelInterfaceExtenders.</returns>
        /// <autogeneratedoc />
        public static ModelInterfaceExtenders UseTokenStringPropertyEditors(this ModelInterfaceExtenders extenders)
        {
            _ = extenders ?? throw new ArgumentNullException(nameof(extenders));

            extenders.Add<IModelMember, ITokenStringModelMember>();
            extenders.Add<IModelPropertyEditor, ITokenStringModelPropertyEditor>();

            return extenders;
        }
    }
}

namespace DevExpress.ExpressApp.Model
{
    /// <summary>
    /// Class XenialTokenEditorsModelTypeList.
    /// </summary>
    /// <autogeneratedoc />
    public static partial class XenialTokenEditorsModelTypeList
    {
        /// <summary>
        /// Uses the token string editor regular types.
        /// </summary>
        /// <param name="types">The types.</param>
        /// <returns>IEnumerable&lt;Type&gt;.</returns>
        /// <autogeneratedoc />
        public static IEnumerable<Type> UseTokenStringEditorRegularTypes(this IEnumerable<Type> types)
            => types.Concat(new[]
            {
                typeof(ITokenStringModelMember),
                typeof(ITokenStringModelPropertyEditor),
                typeof(TokenStringModelMemberDomainLogic),
                typeof(TokenStringEditorTypeVisibilityCalculator)
            });
    }
}
