using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;

using Xenial.Framework.Model.Core;
using Xenial.Framework.TokenEditors.Model;
using Xenial.Framework.TokenEditors.PubTernal;

namespace Xenial.Framework.TokenEditors.Model
{
    /// <summary>   Interface IXenialTokenObjectsModelMember. </summary>
    public interface IXenialTokenObjectsModelMember
    {
        /// <summary>
        /// Gets or sets the token drop down show mode. This value has only an effect in WindowsForms.
        /// </summary>
        ///
        /// <value> The token drop down show mode. </value>

        [ModelBrowsable(typeof(XenialTokenObjectsEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenObjectsPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenObjectsPropertyEditor + "." + nameof(XenialTokenObjectsDropDownShowMode))]
        [Description("Gets or sets the token drop down show mode.\r\nThis value has only an effect in WindowsForms")]
        [DisplayName("DropDownShowMode")]
        TokenDropDownShowMode? XenialTokenObjectsDropDownShowMode { get; set; }

        /// <summary>   Gets or sets the token popup filter mode. </summary>
        ///
        /// <value> The token popup filter mode. </value>

        [ModelBrowsable(typeof(XenialTokenObjectsEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenObjectsPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenObjectsPropertyEditor + "." + nameof(XenialTokenObjectsPopupFilterMode))]
        [Description("Gets or sets the token popup filter mode.")]
        [DisplayName("PopupFilterMode")]
        TokenPopupFilterMode? XenialTokenObjectsPopupFilterMode { get; set; }
    }

    /// <summary>   Interface IXenialTokenObjectsModelPropertyEditor. </summary>
    public interface IXenialTokenObjectsModelPropertyEditor
    {
        /// <summary>
        /// Gets or sets the token drop down show mode. This value has only an effect in WindowsForms.
        /// </summary>
        ///
        /// <value> The token drop down show mode. </value>

        [ModelValueCalculator(nameof(IModelPropertyEditor.ModelMember), typeof(IXenialTokenObjectsModelMember), nameof(IXenialTokenObjectsModelMember.XenialTokenObjectsDropDownShowMode))]
        [ModelBrowsable(typeof(XenialTokenObjectsEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenObjectsPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenObjectsPropertyEditor + "." + nameof(XenialTokenObjectsDropDownShowMode))]
        [Description("Gets or sets the token drop down show mode.\r\nThis value has only an effect in WindowsForms")]
        [DisplayName("DropDownShowMode")]
        TokenDropDownShowMode? XenialTokenObjectsDropDownShowMode { get; set; }

        /// <summary>   Gets or sets the token popup filter mode. </summary>
        ///
        /// <value> The token popup filter mode. </value>

        [ModelValueCalculator(nameof(IModelPropertyEditor.ModelMember), typeof(IXenialTokenObjectsModelMember), nameof(IXenialTokenObjectsModelMember.XenialTokenObjectsPopupFilterMode))]
        [ModelBrowsable(typeof(XenialTokenObjectsEditorTypeVisibilityCalculator))]
        [Category(TokenEditorAliases.TokenObjectsPropertyEditor)]
        [ModelPersistentName(TokenEditorAliases.TokenObjectsPropertyEditor + "." + nameof(XenialTokenObjectsPopupFilterMode))]
        [Description("Gets or sets the token popup filter mode.")]
        [DisplayName("PopupFilterMode")]
        TokenPopupFilterMode? XenialTokenObjectsPopupFilterMode { get; set; }
    }

    /// <summary>
    /// Class TokenObjectsEditorTypeVisibilityCalculator. This class cannot be inherited. Implements
    /// the <see cref="Xenial.Framework.Model.Core.EditorTypeVisibilityCalculator" />
    /// </summary>
    ///
    /// <seealso cref="EditorTypeAliasVisibilityCalculator"/>
    /// <seealso cref="Xenial.Framework.Model.Core.EditorTypeVisibilityCalculator"> <autogeneratedoc /></seealso>

    public sealed class XenialTokenObjectsEditorTypeVisibilityCalculator : EditorTypeAliasVisibilityCalculator
    {
        /// <summary>   Gets the name of the editor alias. </summary>
        ///
        /// <value> The name of the editor alias. </value>

        protected override string EditorAliasName => TokenEditorAliases.TokenObjectsPropertyEditor;
    }

#pragma warning disable CA1707 //Convention by XAF
    /// <summary>   Class TokenObjectsModelMemberDomainLogic. </summary>
    [DomainLogic(typeof(IXenialTokenObjectsModelMember))]
    public static class XenialTokenObjectsModelMemberDomainLogic
    {
        /// <summary>   Gets the token drop down show mode. </summary>
        ///
        /// <exception cref="ArgumentNullException">    Thrown when one or more required arguments are
        ///                                             null. </exception>
        ///
        /// <param name="modelMember">  The model member. </param>
        ///
        /// <returns>   DevExpress.Persistent.Base.TokenDropDownShowMode?. </returns>

        public static TokenDropDownShowMode? Get_XenialTokenObjectsDropDownShowMode(IModelMember modelMember)
        {
            _ = modelMember ?? throw new ArgumentNullException(nameof(modelMember));
            var attribute = modelMember.MemberInfo.FindAttribute<TokenObjectsEditorAttribute>();
            if (attribute is not null)
            {
                return attribute.DropDownShowMode;
            }
            return null;
        }

        /// <summary>   Gets the token popup filter mode. </summary>
        ///
        /// <exception cref="ArgumentNullException">    Thrown when one or more required arguments are
        ///                                             null. </exception>
        ///
        /// <param name="modelMember">  The model member. </param>
        ///
        /// <returns>   DevExpress.Persistent.Base.TokenPopupFilterMode?. </returns>

        public static TokenPopupFilterMode? Get_XenialTokenObjectsPopupFilterMode(IModelMember modelMember)
        {
            _ = modelMember ?? throw new ArgumentNullException(nameof(modelMember));
            var attribute = modelMember.MemberInfo.FindAttribute<TokenObjectsEditorAttribute>();
            if (attribute is not null)
            {
                return attribute.PopupFilterMode;
            }
            return null;
        }
    }
#pragma warning restore CA1707
}

namespace DevExpress.ExpressApp.Model
{
    /// <summary>
    /// Class ModelInterfaceExtendersLayoutBuilderExtensions.
    /// </summary>
    /// <autogeneratedoc />
    public static partial class ModelInterfaceExtendersTokenEditorsExtensions
    {
        /// <summary>   Uses the token objects property editors. </summary>
        ///
        /// <exception cref="ArgumentNullException">    Thrown when one or more required arguments are
        ///                                             null. </exception>
        ///
        /// <param name="extenders">    The extenders. </param>
        ///
        /// <returns>   DevExpress.ExpressApp.Model.ModelInterfaceExtenders. </returns>

        public static ModelInterfaceExtenders UseTokenObjectsPropertyEditors(this ModelInterfaceExtenders extenders)
        {
            _ = extenders ?? throw new ArgumentNullException(nameof(extenders));

            extenders.Add<IModelMember, IXenialTokenObjectsModelMember>();
            extenders.Add<IModelPropertyEditor, IXenialTokenObjectsModelPropertyEditor>();

            return extenders;
        }
    }
}

namespace DevExpress.ExpressApp.Model
{
    /// <summary>
    /// Class XenialTokenEditorsModelTypeList.
    /// </summary>
    /// <autogeneratedoc />
    public static partial class XenialTokenEditorsModelTypeList
    {
        /// <summary>   Uses the token objects editor regular types. </summary>
        ///
        /// <param name="types">    The types. </param>
        ///
        /// <returns>   System.Collections.Generic.IEnumerable&lt;System.Type&gt;. </returns>

        public static IEnumerable<Type> UseXenialTokenObjectsEditorRegularTypes(this IEnumerable<Type> types)
            => types.Concat(new[]
            {
                typeof(IXenialTokenObjectsModelMember),
                typeof(IXenialTokenObjectsModelPropertyEditor),
                typeof(XenialTokenObjectsModelMemberDomainLogic),
                typeof(XenialTokenObjectsEditorTypeVisibilityCalculator)
            });
    }
}

