using System;
using System.Linq;

using DevExpress.ExpressApp.Win.Editors;
using DevExpress.XtraEditors;

using Xenial.Framework.LabelEditors.Win.Editors;

namespace Xenial.Framework.LabelEditors.Win.Editors
{
    /// <summary>
    /// Class StepProgressBarEnumPropertyEditor. Implements the
    /// <see cref="DevExpress.ExpressApp.Win.Editors.WinPropertyEditor" />
    /// </summary>
    ///
    /// <seealso cref="WinPropertyEditor"/>
    /// <seealso cref="DevExpress.ExpressApp.Win.Editors.WinPropertyEditor">    <autogeneratedoc /></seealso>

    [XenialCheckLicense]
    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="DevExpress.ExpressApp.Win.Editors.WinPropertyEditor" />
    public class LabelStringPropertyEditor : WinPropertyEditor
    //TODO: InplaceEditSupport
    //, IInplaceEditSupport
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LabelStringPropertyEditor"/> class.
        /// </summary>
        /// <param name="objectType">Type of the object.</param>
        /// <param name="model">The model.</param>
        public LabelStringPropertyEditor(Type objectType, DevExpress.ExpressApp.Model.IModelMemberViewItem model)
            : base(objectType, model)
            => ControlBindingProperty = nameof(Control.Text);

        /// <summary>
        /// Creates the control core.
        /// </summary>
        /// <returns></returns>
        protected override object CreateControlCore()
        {
            var control = new LabelControl
            {
                AllowHtmlString = true,
            };

            control.Appearance.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            return control;
        }

        /// <summary>
        /// Provides access to the control that represents the current Property Editor in a UI.
        /// </summary>
        /// <value>
        /// A <see cref="T:System.Windows.Forms.Control" /> object used to display the current Property Editor in a UI.
        /// </value>
        public new LabelControl Control => (LabelControl)base.Control;
    }
}

namespace DevExpress.ExpressApp.Editors
{
    /// <summary>   Class LabelStringPropertyEditorWinExtensions. </summary>
    public static partial class LabelStringPropertyEditorWinExtensions
    {
        /// <summary>   Uses the label string property editors windows forms. </summary>
        ///
        /// <exception cref="ArgumentNullException">    Thrown when one or more required arguments are
        ///                                             null. </exception>
        ///
        /// <param name="editorDescriptorsFactory"> The editor descriptors factory. </param>
        ///
        /// <returns>   EditorDescriptorsFactory. </returns>

        public static EditorDescriptorsFactory UseLabelStringPropertyEditorsWin(this EditorDescriptorsFactory editorDescriptorsFactory)
        {
            _ = editorDescriptorsFactory ?? throw new ArgumentNullException(nameof(editorDescriptorsFactory));

            editorDescriptorsFactory.RegisterPropertyEditor(
                Xenial.Framework.LabelEditors.PubTernal.LabelEditorAliases.LabelStringPropertyEditor,
                typeof(string),
                typeof(LabelStringPropertyEditor),
                false
            );

            return editorDescriptorsFactory;
        }
    }
}
