using Xenial.Framework.Layouts.Items.Base;

namespace Xenial.Framework.Layouts.Items
{
    /// <summary>
    /// 
    /// </summary>
    [XenialCheckLicence]
    public partial record LayoutLabelItem : LayoutViewItem
    {
        /// <summary>
        /// Gets or sets the text.
        /// </summary>
        /// <value>The name of the image.</value>
        /// <autogeneratedoc />
        public string Text { get; init; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutStaticImageItem"/> class.
        /// </summary>
        /// <param name="text">The text.</param>
        /// <autogeneratedoc />
        public LayoutLabelItem(string text)
            : base(text)
                => Text = text;
    }
}
