using System;
using System.Collections.Generic;
using System.Text;

using DevExpress.ExpressApp.Model;

using Xenial.Framework.Layouts.Items.Base;

namespace Xenial.Framework.Layouts.Items
{
    /// <summary>
    /// 
    /// </summary>
    [XenialCheckLicence]
    public partial record LayoutStaticImageItem : LayoutViewItem
    {
        /// <summary>
        /// Gets or sets the name of the image.
        /// </summary>
        /// <value>The name of the image.</value>
        /// <autogeneratedoc />
        public string ImageName { get; init; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutStaticImageItem"/> class.
        /// </summary>
        /// <param name="imageName">Name of the image.</param>
        /// <autogeneratedoc />
        public LayoutStaticImageItem(string imageName)
            : base(imageName)
                => ImageName = imageName;

        /// <summary>
        /// Gets or sets the image options.
        /// </summary>
        /// <value>The image options.</value>
        /// <autogeneratedoc />
        public Action<IModelStaticImage>? ImageOptions { get; set; }
    }

    /// <summary>
    /// 
    /// </summary>
    [XenialCheckLicence]
    public partial record LayoutStaticTextItem : LayoutViewItem
    {
        /// <summary>
        /// Gets or sets the text.
        /// </summary>
        /// <value>The name of the image.</value>
        /// <autogeneratedoc />
        public string Text { get; init; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutStaticTextItem"/> class.
        /// </summary>
        /// <param name="text">The text.</param>
        /// <autogeneratedoc />
        public LayoutStaticTextItem(string text)
            : base(text)
                => Text = text;

        /// <summary>
        /// Gets or sets the text options.
        /// </summary>
        /// <value>The text options.</value>
        /// <autogeneratedoc />
        public Action<IModelStaticText>? TextOptions { get; set; }
    }
}
