using System;
using System.Collections;
using System.Collections.Generic;

using DevExpress.ExpressApp.Layout;
using DevExpress.ExpressApp.Model;
using DevExpress.Utils;

using Xenial.Framework.Layouts.Items.Base;
using Xenial.Framework.Layouts.Items.PubTernal;

using Locations = DevExpress.Persistent.Base.Locations;

#pragma warning disable CA1710 //Rename Type to end in Collection -> By Design
#pragma warning disable CA2227 //Collection fields should not have a setter: By Design

namespace Xenial.Framework.Layouts.Items
{
    /// <summary>
    /// 
    /// </summary>
    [XenialCheckLicence]
    public sealed partial record LayoutTabbedGroupItem
        : LayoutItemNode,
        IEnumerableLayoutItemNode<LayoutTabGroupItem>,
        ILayoutElementWithCaption,
        ILayoutElementWithCaptionOptions
    {
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>Xenial.Framework.Layouts.Items.LayoutTabbedGroupItem.</returns>
        /// <autogeneratedoc />
        public static LayoutTabbedGroupItem Create()
            => new();

        /// <summary>
        /// Creates the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Xenial.Framework.Layouts.Items.LayoutTabbedGroupItem.</returns>
        /// <autogeneratedoc />
        public static LayoutTabbedGroupItem Create(string id)
            => new(id);

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutTabbedGroupItem"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public LayoutTabbedGroupItem() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutTabbedGroupItem"/> class.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <autogeneratedoc />
        public LayoutTabbedGroupItem(string id)
            => Id = Slugifier.GenerateSlug(id);

        /// <summary>
        /// Gets the is leaf.
        /// </summary>
        /// <value>The is leaf.</value>
        /// <autogeneratedoc />
        internal override bool IsLeaf => false;

        /// <summary>
        /// Gets the children.
        /// </summary>
        /// <value>The children.</value>
        /// <autogeneratedoc />
        public LayoutItemCollection<LayoutTabGroupItem> Children { get; set; } = new LayoutItemCollection<LayoutTabGroupItem>();

        /// <summary>
        /// Adds the specified node.
        /// </summary>
        /// <param name="item">The node.</param>
        /// <autogeneratedoc />
        public void Add(LayoutTabGroupItem item)
        {
            _ = item ?? throw new ArgumentNullException(nameof(item));

            if (!Equals(item.Parent))
            {
                item.Parent = this;
            }
            if (!Children.Contains(item))
            {
                Children.Add(item);
            }
        }

        /// <summary>
        /// Adds the specified items.
        /// </summary>
        /// <param name="items">The items.</param>
        /// <autogeneratedoc />
        public void Add(params LayoutTabGroupItem[] items)
        {
            foreach (var item in items)
            {
                Add(item);
            }
        }

        /// <summary>
        /// Removes the specified node.
        /// </summary>
        /// <param name="item">The node.</param>
        /// <autogeneratedoc />
        public bool Remove(LayoutTabGroupItem item)
        {
            _ = item ?? throw new ArgumentNullException(nameof(item));

            if (Children.Contains(item))
            {
                var value = Children.Remove(item);
                item.Parent = null;
                return value;
            }
            return false;
        }

        /// <summary>
        /// Clears this instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Clear()
            => Children.Clear();

        /// <summary>
        /// Determines whether this instance contains the object.
        /// </summary>
        /// <param name="item">The node.</param>
        /// <returns>bool.</returns>
        /// <autogeneratedoc />
        public bool Contains(LayoutTabGroupItem item)
        {
            _ = item ?? throw new ArgumentNullException(nameof(item));
            return Children.Contains(item);
        }

        IEnumerator IEnumerable.GetEnumerator() => Children.GetEnumerator();
        bool ICollection<LayoutTabGroupItem>.IsReadOnly => ((ICollection<LayoutTabGroupItem>)Children).IsReadOnly;
        int ICollection<LayoutTabGroupItem>.Count => Children.Count;
        IEnumerator<LayoutTabGroupItem> IEnumerable<LayoutTabGroupItem>.GetEnumerator() => Children.GetEnumerator();
        void ICollection<LayoutTabGroupItem>.CopyTo(LayoutTabGroupItem[] array, int arrayIndex) => Children.CopyTo(array, arrayIndex);

        /// <summary>
        /// Gets or sets the direction.
        /// </summary>
        /// <value>The direction.</value>
        /// <autogeneratedoc />
        public FlowDirection Direction { get; init; }

        /// <summary>
        /// Gets or sets the caption.
        /// </summary>
        /// <value>The caption.</value>
        /// <autogeneratedoc />
        public string? Caption { get; set; }

        /// <summary>
        /// Gets or sets the show caption.
        /// </summary>
        /// <value>The show caption.</value>
        /// <autogeneratedoc />
        public bool? ShowCaption { get; set; }

        /// <summary>
        /// Gets or sets the caption horizontal alignment.
        /// </summary>
        /// <value>The caption horizontal align.</value>
        /// <autogeneratedoc />
        public HorzAlignment? CaptionHorizontalAlignment { get; set; }

        /// <summary>
        /// Gets or sets the caption location.
        /// </summary>
        /// <value>The caption location.</value>
        /// <autogeneratedoc />
        public Locations? CaptionLocation { get; set; }

        /// <summary>
        /// Gets or sets the caption vertical alignment.
        /// </summary>
        /// <value>The caption vertical align.</value>
        /// <autogeneratedoc />
        public VertAlignment? CaptionVerticalAlignment { get; set; }

        /// <summary>
        /// Gets or sets the caption word wrap.
        /// </summary>
        /// <value>The caption word wrap.</value>
        /// <autogeneratedoc />
        public WordWrap? CaptionWordWrap { get; set; }

        /// <summary>
        /// Gets or sets the multi line.
        /// </summary>
        /// <value>The multi line.</value>
        /// <autogeneratedoc />
        public bool? MultiLine { get; set; }

        /// <summary>
        /// Gets or sets the tabbed group options.
        /// </summary>
        /// <value>The tabbed group options.</value>
        /// <autogeneratedoc />
        public Action<IModelTabbedGroup>? TabbedGroupOptions { get; set; }
    }
}
