using System;
using System.Collections.Generic;
using System.Text;

using Xenial.Framework.ModelBuilders;

namespace DevExpress.ExpressApp.DC
{
    /// <summary>
    /// Class XpoModelBuilderExtentions.
    /// </summary>
    /// <autogeneratedoc />
    public static partial class TypesInfoExtentions
    {
        /// <summary>
        /// Removes the xpo views from application model.
        /// </summary>
        /// <param name="typesInfo">The types information.</param>
        /// <returns>ITypesInfo.</returns>
        /// <autogeneratedoc />
        public static ITypesInfo RemoveXafViewsFromApplicationModel(this ITypesInfo typesInfo)
        {
            typesInfo
                .CreateModelBuilder<RemoveViewsModelBuilder<NonPersistentBaseObject>>()
                .Build();

            typesInfo
                .CreateModelBuilder<RemoveViewsModelBuilder<NonPersistentObjectImpl>>()
                .Build();

            typesInfo
                .CreateModelBuilder<RemoveViewsModelBuilder<NonPersistentEntityObject>>()
                .Build();

            typesInfo
                .CreateModelBuilder<RemoveViewsModelBuilder<NonPersistentBaseObject>>()
                .Build();

            typesInfo
                .CreateModelBuilder<RemoveViewsModelBuilder<NonPersistentLiteObject>>()
                .Build();

            #region SystemModule

            typesInfo
                .CreateModelBuilder<RemoveViewsModelBuilder<SystemModule.ProcessDataLockingInfoDialogObject>>()
                .Build();

            #endregion

            return typesInfo;
        }
    }
}
