name: docs.xenial.io

on:
  push:
    branches: [ main ]
    tags: [v*]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --unshallow

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x

    - name: Setup .NET6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET7
      uses: actions/setup-dotnet@v1
      with:
        #dotnet-version: 7.0.x
        dotnet-version: '7.0.100-preview.1.22110.4'
        include-prerelease: true
    
    - name: Build
      run: dotnet run --project build/build.csproj docs
      env:
          DEVEXPRESS_NUGET_FEED: ${{secrets.DEVEXPRESS_NUGET_FEED}}

    - uses: actions/upload-artifact@v2.2.4
      with:
        name: docs
        path: artifacts/docs.xenial.io/

    - name: Upload ftp
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # ftp server
        server: ftp.delegate.at
        # ftp username
        username: ${{ secrets.FTP_USER }}
        # ftp password
        password: ${{ secrets.FTP_PASS }}
        # Folder to upload from, must end with trailing slash /
        local-dir: artifacts/docs.xenial.io/
