name: docs.xenial.io

on:
  push:
    branches: [ main ]
    paths: [docs/**/*.*, .github/workflows/docs.yml]
    tags: [v*]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --unshallow

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2

    - name: Setup .NET5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet run --project build/build.csproj docs
      env:
          DEVEXPRESS_NUGET_FEED: ${{secrets.DEVEXPRESS_NUGET_FEED}}

    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: artifacts/docs.xenial.io/

    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        localDir: artifacts/docs.xenial.io
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
